---
title: "RLAB 3 Markdown"
author: "LCP"
date: "1/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=4, fig.height=4, echo = TRUE, warning=FALSE, message=FALSE, comment=NA)
options(digits=3)
```


```{r}
#RLAB #3
#Data=Boilers

setwd("c:/data/CSV")

boilers <- read.csv("boilers.csv", header=TRUE)

names(boilers)

#1. create scatterplots
plot(boilers$Capacity,boilers$ManHours,xlab='Capacity', ylab='Hours', main="Hours vs. Capacity")
plot(boilers$Pressure,boilers$ManHours,xlab='Pressure', ylab='Hours', main="Hours vs. Pressure")

#2. Hypothesized model

#3. linear regression analysis
model <- lm(ManHours~Capacity+Pressure+Capacity*Pressure, data=boilers)
modelsummary <- summary(model)
names(modelsummary)

#4. Model utility
sigma <- modelsummary$sigma
y_bar <- mean(boilers$ManHours)
cv <- (sigma/y_bar)*100
sigma
y_bar
cv

#5. prediction and estimation
newdata <-data.frame(Capacity=441000, Pressure=410)
predict(model, newdata, interval="prediction")
predict(model, newdata, interval="confidence")
```
